const connection = require('../config/connection');
const Trail = require('../models/Trail');
const { ObjectId } = require('mongoose').Types;

async function seedTrails() {
  try {
    await connection;

    const trailData = [
      {
        _id: new ObjectId('647e11311ba1d11e7e07d228'),
        trail: 'Blazing Star State Trail',
        trailUses: ['Hiking', 'Biking', 'In-line skating', 'Wheelchair access'],
        naturalSurface: null,
        groomed: null,
        skiTrail: null,
        atvTrail: null,
        description: 'The Blazing Star State Trail is paved and runs from Albert Lea Lake in Albert Lea to Myre-Big Island State Park, a distance of approximately six miles. The trail currently connects to Albert Lea\'s city trail system. When completed, the Blazing Star State Trail will be approximately 20 miles long and will run from Albert Lea and Austin, connecting to Austin\'s city trail system as well the Shooting Star State Trail.',
        landscape: 'Trail users will enjoy views of rural landscapes along the entire trail. Myre-Big Island State Park affords the opportunity to experience a diversity of natural environments including wetlands, oak savanna, big woods, and prairie. The park is considered one of the many good birding spots in southern Minnesota, especially during spring and fall migration.',
        permits: ['You will need a vehicle permit to park in a state park.', 'No fees or passes are required to use the trail.'],
        parking: ['In Albert Lea, at the Frank Hall Park or East Front Street trailheads.', 'In Myre-Big Island State Park at the Visitor Center, Big Island and White Fox Campground.', 'West of Hayward at the trailhead on Township Road 290.', 'In Hayward at the city trailhead on West Street.'],
        restrooms: ['At Frank Hall Park in Albert Lea', 'At the White Fox Campground in Myre-Big Island State Park'],
        winter: ['Cross-country skiing, snowshoeing, and hiking are permitted winter uses. Trails are not groomed or packed. There is no snowmobiling on the trail.'],
        lat: 43.64428398436928,
        long:  -93.36182640295037,
        map_latitude: 43.63706513557423,
        map_longitude: -93.30820707728195,
        map_zoom: 14,
        map_zoom_embed: 11,
        created_at: '06/07/2023',
        updated_at: '06/07/2023',
      },
      { 
        _id: new ObjectId('647e11311ba1d11e7e07d229'),
        trail: "Brown's Creek State Trail",
        trailUses: ['Hiking', 'Biking', 'In-line skating', 'Horseback', 'Wheelchair access'],
        naturalSurface: null,
        skiTrail: null,
        atvTrail: null,
        description: 'This beautiful trail is 5.9 miles long and connects the Gateway State Trail in the city of Grant to the St. Croix National Scenic Riverway opens in a new browser tab in Stillwater. Situated on a former railroad grade, the trail is generally level and accessible to users of all abilities. The trail connects to local park and trail systems. Purchase and development of this trail was made possible by the Minnesota Environment and Natural Resources Trust Fund, the Legacy Amendment, Washington County, the City of Stillwater, and the Gateway-Brown\'s Creek Trail Association.',
        landscape: 'About two miles of the Brown\'s Creek State Trail are immediately adjacent to Brown\'s Creek, a designated trout stream with a dense broadleaf forest canopy. One mile of the trail corridor parallels the St. Croix River, with spectacular views of the National Scenic Riverway. This is Minnesota\'s only river in the federal Wild and Scenic Rivers system. The trail also passes by an audio listening station, historical markers and buildings and through local parks, golf courses, and a community with historical significance.',
        permits: ['You will need a Horse Pass if you will be horseback riding or carriage driving.', 'No other fees or passes are required to use the trail.'],
        parking: ['Laurel Street East in downtown Stillwater, at the eastern end of the trail.', 'In Brown\'s Creek Nature Preserve, just south of the intersection of McKusick Road and Neal Avenue, halfway along the trail.', 'In Grant, near Lake Masterman on State Highway 96, under the Gateway State Trail bridge.'],
        restrooms: ['1/4 mile south of the eastern end of the trail in downtown Stillwater, at the pedestrian walkway managed by the city.', 'Seasonal portable bathroom in Brown\'s Creek Nature Preserve on Neal Avenue, halfway along the trail.', 'Seasonal portable bathroom about 1/4 mile northeast of the western end of the trail, at the intersection of the Gateway State Trail and State Highway 96.'],
        winter: ['In the winter, the eastern portion of the trail between Laurel Street and Manning Avenue in Stillwater is plowed. The western portion between Manning Avenue in Stillwater and Duluth Junction in Grant is not maintained and can be used by bikers, hikers, snowshoers, and skiers.'],
        lat: 45.061699540579916,
        long: -92.80617117378955,
        map_latitude: 45.07006844427505,
        map_longitude: -92.84348759432623,
        map_zoom: 13,
        map_zoom_embed: 11,
        created_at: '06/07/2023',
        updated_at: '06/07/2023',
      },
      { 
        _id: new ObjectId('647e11311ba1d11e7e07d230'),
        trail: 'Casey Jones State Trail',
        trailUses: ['Hiking', 'Biking', 'In-line skating', 'Horseback','Snowmobiling', 'Wheelchair access'],
        naturalSurface: null,
        skiTrail: null,
        atvTrail: null,
        description: 'The Casey Jones State Trail consists of three segments. The longest segment is 12 miles of former railroad grade between the city of Pipestone and the Pipestone/Murray county line. The eight mile segment from Pipestone to County Road 67 is paved. The next two miles leading into the town of Woodstock have a graded gravel surface, and the remaining two miles have an unmaintained, natural surface. A second, small, natural-surfaced segment runs west one and one-half miles from the city of Lake Wilson. The third portion of the trail is a six mile, paved loop between Lake Shetek State Park and the city of Currie. Horseback riding is not allowed on this portion.',
        landscape: 'The trail connects points of natural interest, such as remnants of tallgrass prairie, wooded ravines, Lake Shetek and the sloughs around it, which are remnants of the glacial landscape that once covered southwestern Minnesota. Historical and cultural sites around the area include sites associated with Laura Ingalls Wilder in Walnut Grove, railroad artifacts in Currie and Tracy, wind towers, and the pipestone quarries in the Pipestone National Monument. The trail is situated in the rolling vastness of the agricultural landscape that characterizes the upper Great Plains, with individual homesteads appearing like islands in a sea of corn and soybeans. The landscape is truly the heartland of America. The seeming infinity and openness to the sky are highlights of this trail.',
        permits: ['You will need a Horse Pass if you will be horseback riding or carriage driving.','You will need a vehicle permit to park in a state park.','Snowmobiles must be registered or have a snowmobile state trail sticker.', 'No other fees or passes are required to use the trail.'],
        parking: ['Pipestone: Parking located off Highway 23.', 'Woodstock: Parking available at the community park.', 'Lake Wilson: Parking available at the community park.', 'Currie: Parking available at the End-O-Line Railroad Park and Museum.', 'Lake Shetek State Park: Parking available.'],
        restrooms: ['Restroom facilities are available along the trail within Lake Shetek State Park.', 'Restrooms are also available at End-O-Line Railroad Park and Museum from May through October.'],
        winter: ['The trail connects with the Grants-in-Aid (GIA) trail system, which provides many miles of groomed snowmobile trails in the area.'],
        lat: 44.00258034841166,
        long: -96.30689282775607,
        map_latitude: 43.99553421551974,
        map_longitude: -95.95659928887873,
        map_zoom: 11,
        map_zoom_embed: 9,
        created_at: '06/07/2023',
        updated_at: '06/07/2023',
      },
      { 
        _id: new ObjectId('647e11311ba1d11e7e07d231'),
        trail: 'Central Lakes State Trail',
        trailUses: ['Hiking', 'Biking', 'In-line skating', 'Snowmobiling', 'Wheelchair access'],
        naturalSurface: null,
        skiTrail: null,
        atvTrail: null,
        description: 'The Central Lakes State Trail is a 55 mile former railroad route turned paved bike trail that runs through three counties and ten communities. This trail begins in the city of Fergus Falls, and ends in the city of Osakis. Trail users will enjoy the many differing landscape views, ranging from open grassland/prairie, lakes, wetlands, farmland, and forested rolling hills',
        landscape: 'The area is historically significant because the Kensington Rune Stone, dated 1362, was found near a small town southwest of Alexandria. An often misunderstood artifact with over 200 medieval runes chiseled in its surface, the Stone suggests Norsemen adventured in the area 130 years before Christopher Columbus. The region is also known for its unique geographic features around Lake Christina, including the Seven Sisters Prairie on the north side of the lake, which is a group of seven, glacially-produced knolls. Lake Christina is an important stop for many species of waterfowl during migration. For more trail information, visit the Central Lakes Trail Association opens in a new browser tab. The Central Lakes State Trail connects to the Lake Wobegon Regional Trail. opens in a new browser tab in Osakis. The Lake Wobegon Trail is a 46-mile, paved trail that leads into the town of St. Joseph, MN',
        permits: ['Snowmobiles must be registered or have a snowmobile state trail sticker.','No other fees or passes are required to use the trail.'],
        parking: ['In Fergus Falls at the Central Lakes State Trail Trailhead, Hwy 210', 'In Fergus Falls in Delagoon City Park', 'In the cities of Dalton, Ashby, Evansville, Brandon, Garfield', 'In Alexandria at Big Ole Park.', 'In Nelson', 'In Osakis by the downtown trailhead (Osakis Information Center).'],
        restrooms: 'Restroom facilities may be available in each of the communities along the trail.',
        winter: ['The trail is groomed for winter snowmobile use by the Otter Country Trails Association opens in a new browser tab and Douglas Area Trails Association opens in a new browser tab. Be aware of local speed limit restrictions. There are no stud restrictions on the Central Lakes State Trail, however, metal studs on tracks are prohibited on the Lake Wobegon Regional Trail from the city of Osakis to St. Joseph.'],
        lat: 46.27341900989875,
        long: -96.04381348278801,
        map_latitude: 45.96361775448329,
        map_longitude: -95.5996652181749,
        map_zoom: 10,
        map_zoom_embed: 8,
        created_at: '06/07/2023',
        updated_at: '06/07/2023',
      },
      { 
        _id: new ObjectId('647e11311ba1d11e7e07d232'),
        trail: 'C.J. Ramstad/North Shore State Trail',
        trailUses: ['Hiking', 'Mountain Biking', 'Horseback','Snowmobiling', 'All-terrain vehicles (ATVs)'],
        naturalSurface: null,
        skiTrail: null,
        atvTrail: null,
        description: 'The C.J. Ramstad/North Shore State Trail is a 146-mile long multi-purpose, natural surface trail from Duluth to Grand Marais. The trail runs through St. Louis, Lake and Cook counties in northeastern Minnesota, winding its way through the forests on the ridgeline overlooking Lake Superior. The trail provides access to some of the most rugged and beautiful scenery in Minnesota. In winter, the trail connects with hundreds of miles of snowmobile club trails and many communities in the area.',
        landscape: 'For most of its length, the trail provides a back-country, wilderness experience. The majority of the trail is in a remote, natural and undeveloped setting with few roads and many river crossings. Native wildlife includes moose, deer, bear, fox, raptors, grouse, waterfowl, songbirds and timber wolves. Views of rivers, lakes, valleys and scenic overlooks are a part of the trail experience, as are logging, forestry, farming, wildlife and fish management, and cabins. Fall colors are usually quite spectacular because the trail follows maple-covered ridges, as well as birch and aspen stands.',
        permits: ['You will need a Horse Pass if you will be horseback riding.','Snowmobiles must be registered or have a snowmobile state trail sticker.Snowmobiles must be registered or have a snowmobile state trail sticker.','Off-highway vehicles require the proper registration. Non-residents must have the correct non-resident OHV trail pass.', 'No other fees or passes are required to use the trail.'],
        parking: ['Duluth parking area: The Martin Road lot is located at the northern edge of Duluth city limits.', 'Normanna Road parking area: Parking is located west of County Road 44.', 'Alger Grade parking area: Parking is located 9 miles north of Two Harbors on County Road 2.', 'Silver Bay parking area: The lot located on Superior National Forest Road #11, 7 miles west of Silver Bay', 'Finland parking area: The trailhead is located 2 miles north of Finland, on County Road 7.', 'Sawbill Trail parking area: A small parking area is located 5 miles north of Tofte on the Sawbill Trail (County Road 2).', 'Caribou Trail parking area: The parking lot is located 7 miles north of Lutsen on the Caribou Trail (County Road 4).'],
        restrooms: 'Restrooms are available at trailhead parking lots and shelters along the trail.',
        winter: null,
        lat: 46.86482819037517,
        long: -92.06941108662431,
        map_latitude: 47.33937407234273,
        map_longitude: -91.34524903394147,
        map_zoom: 9,
        map_zoom_embed: 7,
        created_at: '06/07/2023',
        updated_at: '06/07/2023',
      },
      { 
        _id: new ObjectId('647e11311ba1d11e7e07d233'),
        trail: 'Cuyuna Lakes State Trail',
        trailUses: ['Hiking', 'Biking', 'In-line skating', 'Mountain Biking', 'Wheelchair access'],
        naturalSurface: null,
        skiTrail: null,
        atvTrail: null,
        description: 'The Cuyuna Lakes State Trail is a paved eight-mile trail running from Crosby to Riverton, inside the Cuyuna Country State Recreation Area. One mile passes through the City of Aitkin along State Highway 169. Abandoned by mining companies more than 35 years ago, the state recreation area contains six natural lakes, plus an additional 15 deep lakes that were former mine pits. Stop to fish, explore the Croft Mine, or ride the world-class single track mountain bike trail system with 25 miles of riding and over 30 purpose-built routes for riders at all levels.',
        landscape: 'Twenty-five miles of undeveloped shoreline can be explored by boat or canoe and anglers can cast a line for trout, Northerns, bass, crappies, sunfish, and walleyes.',
        permits: ['If you plan to park in the nearby state recreation area, you will need a vehicle permit.','No other fees or passes are required to use the trail.'],
        parking: ['Croft Mine Historical Park and trail head parking is located in Crosby. Follow Hwy 210/6 north into Crosby and follow the signs to the Croft Mine Historical Park or take 2nd Ave NE north to the "T" and then left to the park.', 'Pennington Mine Lake Public Water Access is northeast of Ironton off of Portsmouth Mine Road.', 'Portsmouth parking area is located at the west side of State Hwy 6 just north of Crosby.', 'Riverton trail head: From Highway 210 and the intersection of County Road 59, go north 1 to the intersection of County Road 128, take a right and go to the intersection of Rowe Road, take a left and the trail parking lot entrance is on the right of Rowe Road'],
        restrooms: ['Portsmouth Campground is a facility for campers near the facility, seasonally open.', 'Most communities provide public restrooms nearby.', 'Public Water Access locations often have seasonal toilets available.'],
        winter: null,
        lat: 46.46181106240843,
        long: -94.04548023608898,
        map_latitude: 46.4814786087474,
        map_longitude: -93.97944568708984,
        map_zoom: 13,
        map_zoom_embed: 11,
        created_at: '06/07/2023',
        updated_at: '06/07/2023',
      },
      { 
        _id: new ObjectId('647e11311ba1d11e7e07d234'),
        trail: 'David Dill/Arrowhead State Trail',
        trailUses: ['Hiking', 'Mountain Biking', 'Horseback','Snowmobiling'],
        naturalSurface: null,
        skiTrail: null,
        atvTrail: null,
        description: 'The 135-mile David Dill/Arrowhead State Trail extends from ten miles west of Tower at the intersection with the Taconite State Trail, to Ericsburg, ten miles south of International Falls. This long-distance, natural surface trail was developed mainly for winter use and is used primarily for snowmobiling. Approximately 69 miles of the trail are suitable for horseback riding, mountain biking and hiking in the summer, but some sections of the trail may be impassable with standing water. Call the nearest Parks and Trails area office prior to your trip to enquire about current trail conditions.',
        landscape: 'The southern part of the trail features rolling hills with numerous lakes and streams. Many of the hills have large areas of exposed rock and enormous boulders. This part is heavily timbered with a mix of hardwoods and conifers. This mix of trees is spectacularly colorful in autumn. The northern part of the trail is relatively flat between International Falls and the Ash River. The higher ground is mainly forested with aspen; lower ground has a mix of spruce and ash. The trail goes through a number of areas that have standing water in the summer, which makes these portions of the trail mostly suited to winter use. The landscape of the area is a result of the underlying geology. The area\'s bedrock formation is known as the Canadian Shield. It was formed by volcanic action approximately 2.7 billion years ago, and is some of the oldest rock on Earth. Later, ancient seas laid down the valuable iron ore that is still mined in the area today. Further volcanic activity swept away the sea and formed two mountain ranges. The advancing and receding of glaciers and millions of years of erosion have worn the mountains down, leaving behind the rugged landscape now found along much of the trail.',
        permits: ['You will need a Horse Pass if you will be horseback riding or carriage driving','You will need a Ski Pass if you will be cross-country skiing on groomed trail. Ungroomed trail does not require a pass.','Snowmobiles must be registered or have a snowmobile state trail sticker.', 'No other fees or passes are required to use the trail.'],
        parking: ['Cook: In town.', 'International Falls: In town.', 'Kabetogama River State Forest: At forest campgrounds.', 'Tower: Trailhead parking 2 miles west of Highway 169 on Highway 1.'],
        restrooms: ['Bear Head Lake State Park: Parking and interpretive center located within the state park.', 'George Washington State Forest: Campgrounds offer seasonal facilities, check ahead.', 'McCarthy Beach State Park: Parking and campgrounds located within the state park.', 'Soudan Underground Mine State Park: Parking and interpretive center located within the state park.'],
        winter: null,
        lat: 48.47407946599386,
        long: -93.49618119194604,
        map_latitude: 48.16353789607789,
        map_longitude: -92.79875594463026,
        map_zoom: 9,
        map_zoom_embed: 7,
        created_at: '06/07/2023',
        updated_at: '06/07/2023',
      },
      { 
        _id: new ObjectId('647e11311ba1d11e7e07d235'),
        trail: 'David Dill/Taconite & Taconite State Trails',
        trailUses: ['Hiking', 'Biking', 'Mountain Biking', 'Horseback','Snowmobiling', 'All Terrain vehicles', 'Off Highway Motorcyle'],
        naturalSurface: null,
        skiTrail: null,
        atvTrail: null,
        description: 'The Taconite State Trail stretches 165 miles from Grand Rapids to Ely and intersects with the David Dill/Arrowhead State Trail just west of Lake Vermillion. The David Dill/Taconite State Trail extends from the David Dill/Arrowhead State Trail to Ely. The first six miles from Grand Rapids are paved for biking and in-line skating. The remainder of the natural surface trail is used primarily for snowmobiling in the winter. The trail goes through a few areas that have standing water in the summer, however portions of the trail are suitable for horseback riding, hiking, and mountain biking. Off-highway vehicle riding is allowed on some trail portions.',
        landscape: 'The Taconite Trail winds through forests of birch and aspen intertwined with pine, leading the visitor by many isolated lakes and streams. From Grand Rapids heading north, you see the impact of the taconite and iron mining industry. In the northern portion of the trail the terrain is rolling and tree covered as it winds through state and national forest land. Trail users may see a ridge of solid white pine changing to a ravine of mixed hardwoods, then a ridge of aspen, birch and basswood blended with maples. At the trail intersection east of the David Dill/Arrowhead State Trail, this segment is called the David Dill/Taconite State Trail. Eight trail waysides and picnic facilities offer scenic vistas of the hills, lakes and rivers of this area. The trail links to Bear Head Lake, Lake Vermilion-Soudan Underground Mine, and McCarthy Beach state parks. The landscape in and around Bear Head Lake State Park is very rolling and rocky, with elevations ranging from 1,450 - 1,590 feet. The landscape of the area is a result of the underlying geology. The area\'s bedrock formation is known as the Canadian Shield. It was formed by volcanic action approximately 2.7 billion years ago, and is some of the oldest rock on Earth. Later, ancient seas laid down the valuable iron ore that is still mined in the area today. Further volcanic activity swept away the sea and formed two mountain ranges. The advancing and receding of glaciers and millions of years of erosion have worn the mountains down, leaving behind the rugged landscape now found along much of the trail.',
        permits: ['You will need a Horse Pass if you will be horseback riding or carriage driving.','Snowmobiles must be registered or have a snowmobile state trail sticker.','No other fees or passes are required to use the trail.'],
        parking: ['McCarthy Beach State Park', 'Minnesota Highway 73', 'U.S. Highway 53', 'Minnesota Highway 1', 'Minnesota Highway 169, Peyla', 'Minnesota Highway 169, Peyla'],
        restrooms: ['Bear Head Lake State Park: Parking and interpretive center located within the state park.', 'George Washington State Forest: Campgrounds offer seasonal facilities, check ahead.', 'McCarthy Beach State Park: Parking and campgrounds located within the state park.', 'Soudan Underground Mine State Park: Parking and interpretive center located within the state park. Restrooms and amenities are also available in the towns along the trail.'],
        winter: null,
        lat: 47.77751402852817,
        long: -92.40426480469272,
        map_latitude: 47.79672221171079,
        map_longitude: -92.08967242347464,
        map_zoom: 11,
        map_zoom_embed: 9,
        created_at: '06/07/2023',
        updated_at: '06/07/2023',
      },
      { 
        _id: new ObjectId('647e11311ba1d11e7e07d236'),
        trail: 'Douglas State Trail',
        trailUses: ['Hiking', 'Biking', 'In-line skating', 'Horseback','Snowmobiling', 'Wheelchair access'],
        naturalSurface: null,
        skiTrail: null,
        atvTrail: null,
        description: 'The Douglas State Trail is a 12.5 mile, multiple-use trail developed on an abandoned railroad grade. It is generally level and accessible. There are two separate treadways: one is paved for bicyclists and hikers; the other is natural surface for horseback riders and snowmobilers. The trail begins in northwestern Rochester, passes through the small town of Douglas, and ends in Pine Island.',
        landscape: 'This trail offers outstanding rural scenery and travels through some of the richest agricultural land in Minnesota. You will pass through a scenic mix of forest, rolling fields and pastures. Partridge and pheasant live in the woods, and toward Rochester, geese become more abundant. Little-used county roads offer opportunity to plan a circular route.',
        permits: ['You will need a Horse Pass if you will be horseback riding or carriage driving.','Snowmobiles must be registered or have a snowmobile state trail sticker.','No other fees or passes are required to use the trail.'],
        parking: ['Rochester: From U.S. Highway 52, take the CSAH 22 (55th Street) exit; then west and south on CSAH 22 approximately two miles to Olmsted County Road 4; then east .3 miles to the Rochester trailhead.', 'Douglas: From U.S. Highway 52, turn west on Olmsted County Road 14; then west on Olmsted County Road 14 approximately three miles to the Douglas trailhead.', 'Pine Island: From U.S. Highway 52, take Goodhue County Road 11 approximately 1/2 mile to the Pine Island City Park trailhead.'],
        restrooms: ['Toilet facilities are available at each of the trailhead accesses listed under Parking.'],
        winter: ['This trail is not groomed for skiing. Snowmobilers should use the second treadway, which is clearly marked. A snowmobile must be registered or have a snowmobile state trail sticker.'],
        lat: 44.20345759247195,
        long: -92.64328667895369,
        map_latitude: 44.12708100844235,
        map_longitude: -92.58810673193301,
        map_zoom: 12,
        map_zoom_embed: 10,
        created_at: '06/07/2023',
        updated_at: '06/07/2023',
      },
      { 
        _id: new ObjectId('647e11311ba1d11e7e07d237'),
        trail: 'Gateway State Trail',
        trailUses: ['Hiking', 'Biking', 'In-line skating', 'Horseback', 'Wheelchair access'],
        naturalSurface: null,
        skiTrail: null,
        atvTrail: null,
        description: 'The Gateway State Trail is an 18 mile multiple use trail that begins in the city of St. Paul, travels northeast through the cities of Maplewood, North St. Paul, and Oakdale, through Washington County, and ends at Pine Point Regional Park, just four miles northwest of the city of Stillwater. Located on a former Soo Line Railroad grade, the trail is generally level and wheelchair accessible. East of I-694, an adjacent unpaved trail provides ten miles of horseback riding and carriage driving.',
        landscape: 'This paved trail passes through a cross-section of urban areas, parks, lakes, wetlands and fields in Ramsey and Washington Counties. Many trail users are surprised to find rural landscapes so close to the metro area. Others appreciate the access it provides to downtown St. Paul and the State Capitol Complex. The Gateway also provides connections to many local and regional trails, including Phalen-Keller Regional Park and the Bruce Vento Regional Trail.',
        permits: ['You will need a Horse Pass if you will be horseback riding or carriage driving.','You will need a Ski Pass if you will be skiing on a groomed track. Ungroomed tracks do not require a pass.','No other fees or passes are required to use the trail.'],
        parking: ['The North Saint Paul Trailhead, between First Street and Second Street just north of Seventh Avenue, next to the wind turbine', 'Flicek Park (City of Maplewood)', 'Maplewood Community Center, south of the intersection of County Road B and White Bear Avenue', 'Highway 36 and 2nd Street in North St. Paul', 'At Arlington Avenue','55th Street, east of Hadley Avenue (southwest corner of Highway 36 and I-694)', 'Mahtomedi Athletic Fields – Green Lot (north of Hwy. 12, designated trail parking spots only)', 'Jamaca Avenue (at Jeffrey Avenue)', 'Near Lake Masterman on State Highway 96 in Grant, under the Gateway State Trail bridge', 'Pine Point Regional Park, five miles north of Stillwater (fee charged)', 'Parking is also available along city streets that cross the trail'],
        restrooms: ['Parking lot at 55th St., east of Hadley', 'Jamaca Ave. (May-October only)', 'Hwy 36 and 2nd Street in North St. Paul', 'Hwy 96, under the trail bridge (May-October only)', 'Lansing Ave. (May-October only)', 'Pine Point Regional Park', 'Other adjacent city and regional parks along the trail'],
        winter: ['In the winter, the western portion of the trail between Cayuga Street in St. Paul and Jamaca Avenue in Grant is plowed.  The eastern portion between Jamaca Avenue and Pine Point Regional Park is not maintained and can be used by bikers, hikers, snowshoers, and skiers.'],
        lat: 44.976049,
        long: -93.140147,
        map_latitude: 44.976049,
        map_longitude: -93.140147,
        map_zoom: 11,
        map_zoom_embed: 11,
        created_at: '06/07/2023',
        updated_at: '06/07/2023',
      },
      { 
        _id: new ObjectId('647e11311ba1d11e7e07d238'),
        trail: 'Gitchi-Gami State Trail',
        trailUses: ['Hiking', 'Biking', 'In-line skating', 'Skiing', 'Wheelchair access'],
        naturalSurface: null,
        skiTrail: null,
        atvTrail: null,
        description: 'Several segments of the Gitchi-Gami State Trail have been completed, totaling over 33 miles. When complete, the trail will be an 86 mile paved trail for non-motorized use, connecting Two Harbors to Grand Marais along the North Shore of Lake Superior. Much of the trail will be located in abandoned segments or right-of-way on Highway 61, while other segments will allow you to sample a diversity of the North Shore\'s varied environments.',
        landscape: 'This trail will eventually connect five state parks, several communities, four Scientific and Natural Areas, numerous historic sites, and provide vistas of Lake Superior. Trail users will travel through birch and aspen forests, cross numerous cascades and waterfalls, travel through charming and historic towns, and have the opportunity to access beaches of Lake Superior.',
        permits: ['No special fees or passes are required to use the trail.','You will need a vehicle permit if you want to park in a state park.','Electric-assisted bicycles with pedals are allowed on state trails without the use of a permit. Power output cannot exceed 1,000 watts and may not exceed speeds of 20 miles per hour.'],
        parking: ['Silver Creek Cliff wayside rest, on the east side of the Silver Creek Cliff tunnel.', 'Gooseberry Falls State Park campground, picnic area, visitor center, and Gitchi-Gami State Trail trailhead', 'Twin Points public water access', 'Iona\'s Beach Scientific and Natural Area', 'Split Rock Lighthouse State Park trail center', 'Wayside rest near the Beaver River in Beaver Bay', 'Silver Bay hockey arena', 'MNDOT wayside on the east side of Schroeder', 'Temperance River State Park', 'Tofte town park off Sawbill Trail', 'Ski Hill Road trailhead in Lutsen', 'Grand Marais public water access near the U.S. Coast Guard station'],
        restrooms: ['Restrooms and amenities are also available in the towns of Two Harbors, Castle Danger, Beaver Bay, Silver Bay, Schroeder, Tofte, Lutsen and Grand Marais', 'Cascade River State Park', 'Temperance River State Park', 'George Crosby Manitou State Park', 'Tettegouche State Park', 'Split Rock Lighthouse State Park', 'Gooseberry Falls State Park'],
        winter: null,
        lat: 47.556709,
        long: -90.8748,
        map_latitude: 47.556709,
        map_longitude: -90.8748,
        map_zoom: 11,
        map_zoom_embed: 11,
        created_at: '06/07/2023',
        updated_at: '06/07/2023',
      },
      { 
        _id: new ObjectId('647e11311ba1d11e7e07d239'),
        trail: 'Glacial Lakes State Trail',
        trailUses: ['Hiking', 'Biking', 'In-line skating', 'Mountain Miking', 'Horseback','Snowmobiling', 'Wheelchair access'],
        naturalSurface: null,
        skiTrail: null,
        atvTrail: null,
        description: 'The Glacial Lakes State Trail is located on a former Burlington Northern Railroad grade, and is generally level and wheelchair accessible. The trail is paved for 22 miles between Willmar, Spicer, New London, Hawick, and the Kandiyohi/Stearns County line. An additional 7.5 miles from Roscoe to Cold Spring is also paved. The many lakes make this area a popular tourist destination. The towns along the trail provide access points, rest stops, and other services to trail users.',
        landscape: 'The gently rolling topography of central Minnesota was created by glaciers retreating 10,000 years ago. The trail cuts across the border between Minnesota\'s western tallgrass prairie and eastern deciduous forest. Though much of the area has been cultivated, remnants of virgin prairie, wetlands, and scattered woodlots can still be found along the railroad right-of-way. Whitetail deer, numerous small mammals, birds, reptiles, and butterflies can be seen along the trail. Between the Stearns/Kandiyohi County line to Roscoe, the trail is relatively undeveloped. Some railroad bridges are closed.',
        permits: ['You will need a Horse Pass if you will be horseback riding or carriage driving.','Snowmobiles must be registered or have a snowmobile state trail sticker.', 'No other fees or passes are required to use the trail.'],
        parking: ['Willmar: Take Highway 12 east to County Road 9. Turn north (left) and go two miles to the parking lot on west (left) at the Civic Center.', 'Spicer: At the junction of Highway 23 and County Road 10. Parking lot is west off 23.', 'East Nest Lake Public Water Access: Two miles north of Spicer on Highway 23 and 1/2 mile west on the Township Road.', 'New London: 1 mile northeast of Main Street on County Road 31, at the intersection of River View Lane.', 'Hawick: North side of town, at the intersection of Highway 23 and County Road 2.', 'Richmond: Off Highway 23. Go north one block on Central Avenue South.'],
        restrooms: ['North of County Road 26, parking area 3/4 mile', 'North of Country Road 31 (Clark Trailhead) one mile', 'Nest Lake East Public Water Access', 'Hawick Trailhead'],
        winter: 'The trail is groomed for winter snowmobile use within Kandiyohi County. In Stearns County, snowmobile use is allowed on signed sections only.',
        lat: 45.541313,
        long: -95.531502,
        map_latitude: 45.541313,
        map_longitude: -95.531502,
        map_zoom: 11,
        map_zoom_embed: 11,
        created_at: '06/07/2023',
        updated_at: '06/07/2023',
      },
      { 
        _id: new ObjectId('647e11311ba1d11e7e07d240'),
        trail: 'Goodhue Pioneer State Trail',
        trailUses: ['Hiking', 'Biking', 'In-line skating', 'Horseback','Snowmobiling', 'Wheelchair access'],
        naturalSurface: null,
        skiTrail: null,
        atvTrail: null,
        description: 'When complete, the Goodhue Pioneer State Trail will connect the cities of Red Wing, Goodhue, Zumbrota, Mazeppa, Bellechester, and Pine Island for a distance of 47 miles. It will be a part of a trail system that connects two very popular and well-used trails, the Cannon Valley Regional Trail in Red Wing, and the Douglas State Trail in Pine Island. This trail is popular with hikers, bikers, horseback riders and snowmobilers.',
        landscape: 'This trail passes through a scenic mix of tall grass prairies, maple and basswood forests, and oak savanna. Deer, fox, wild turkeys, beavers, partridge, pheasant, and opossum can often be seen from the trail. Bald eagles nest along the Mississippi River and can be spotted just about year-round.',
        permits: ['You will need a Horse Pass if you will be horseback riding or carriage driving.','Snowmobiles must be registered or have a snowmobile state trail sticker.', 'No other fees or passes are required to use the trail.'],
        parking: ['in the city of Red Wing', 'in the Hay Creek Unit of the Richard J. Dorer State Forest', 'in the southern portion of the Covered Bridge Park, in the city of Zumbrota'],
        restrooms: ['in the Hay Creek Unit of the Richard J. Dorer State Forest', 'in the cities of Red Wing and Zumbrota'],
        winter: ['In the south segment, snowmobilers can use the paved trail beginning in the city of Zumbrota and heading north for 4.5 miles. This section is part of the grants-in-aid snowmobile trail system in the winter.', 'In the north segment, snowmobilers can use the grass treadway from Red Wing to Hay Creek (the same trail that is open to horseback riding in the warmer months).'],
        lat: 44.4016511631,
        long: 92.6219534918,
        map_latitude: 44.4016511631,
        map_longitude: 92.6219534918,
        map_zoom: 11,
        map_zoom_embed: 11,
        created_at: '06/07/2023',
        updated_at: '06/07/2023',
      },
      { 
        _id: new ObjectId('647e11311ba1d11e7e07d241'),
        trail: 'Great River Ridge State Trail',
        trailUses: ['Hiking', 'Biking', 'In-line skating', 'Horseback','Snowmobiling', 'Wheelchair access'],
        naturalSurface: null,
        skiTrail: null,
        atvTrail: null,
        description: 'Located in the beautiful southeastern Minnesota river valley, the Great River Ridge State Trail follows a former railroad grade with picturesque views of river bluffs. The trail is generally level and accessible, and is popular for bicycling, hiking, in-line skating, horseback riding and snowmobiling. When complete, the trail will be paved for 15 miles and will connect the cities of Plainview and Eyota. Currently, 13 miles of paved trail begins in Plainview, travels south through the town of Elgin, and ends at County Road 9.',
        landscape: 'Quiet city streets allow users to explore the towns along the way. Plainview is known as the agricultural hub of the area, and has additional opportunity for recreation in its eight city parks. Carley State Park and Whitewater State Park are nearby. Future plans include extension to Carley State Park.',
        permits: ['You will need a Horse Pass if you will be horseback riding or carriage driving.','Snowmobiles must be registered or have a snowmobile state trail sticker.', 'No other fees or passes are required to use the trail.'],
        parking: ['Plainview: Parking lot is at trailhead on 3rd St. SW.', 'Elgin: Parking is available in town.', 'Eyota: Parking lot on County Road 9.'],
        restrooms: ['Carley State Park: (vehicle permit required)'],
        winter: ['The trail offers a dual, natural surface treadway from Elgin to County Road 9 that is used for snowmobiling in the winter.'],
        lat: 44.02136,
        long: -92.2554,
        map_latitude: 44.02136,
        map_longitude: -92.2554,
        map_zoom: 11,
        map_zoom_embed: 11,
        created_at: '06/07/2023',
        updated_at: '06/07/2023',
      },
      { 
        _id: new ObjectId('647e11311ba1d11e7e07d242'),
        trail: 'Harmony-Preston Valley State Trail',
        trailUses: ['Hiking', 'Biking', 'In-line skating', 'Horseback','Snowmobiling', 'Wheelchair access'],
        naturalSurface: null,
        skiTrail: null,
        atvTrail: null,
        description: 'The paved Harmony-Preston Valley State Trail is a beautiful 18-mile multiple use trail that connects the communities of Harmony and Preston with the Root River State Trail in southeastern Minnesota\'s Blufflands region. In the summer the trail is used mainly for hiking, biking and in-line skating. The trail is groomed for cross-country skiing in winter.',
        landscape: `The trail rises and falls with the bluffs, winding through historic towns tucked into hillsides, past rolling farm fields, milling districts, and relics of the railroad's heyday. Lush and verdant stretches offer views of the area's natural beauty. 
          The northern two-thirds of this trail is constructed on a former railroad and is generally level and wheelchair accessible. This section of the trail follows or crosses Watson Creek, the South Branch of the Root River, and Camp Creek, passing through a variety of wooded areas and farmland. Three fishing platforms provide access to trout fishing in Camp Creek, just outside Preston.        
          The southern segment between County Road 16 and Harmony was not constructed on an abandoned railroad, and is comparatively more challenging. This portion of the trail climbs out of the river valley and travels along the ridge line between the valleys, including one rather strenuous incline that may not be suitable for all users.        
          Although Harmony and Preston were both settled in the 1850's, the cities are quite different in appearance. Harmony was developed upon the agricultural uplands above the Root River Valley and is home to both traditional Amish communities and green industries. Preston is located within the south branch of the Root River Valley and had an active milling community when it was settled in 1853; today the town is the county seat of Fillmore County. Each community speaks to a very different time in Minnesota's history, with several historical buildings and interpretive opportunities.        
          Wildlife is abundant along the trail, and sightings of wild turkey, deer, hawks and turkey vultures are common. Rattlesnakes can occasionally be found on rock outcrops, along the river bottoms, or sunning themselves on the trail. They are a state threatened and protected species, and should be left alone.`,
        permits: ['You will need a Ski Pass for cross-country skiing on a groomed trail. Ungroomed trails do not require a pass.', 'No other fees or passes are required to use the trail.'],
        parking: ['Harmony: From Highway 52 take 4th Street NW approximately 1/2 mile west to the parking lot.', 'Preston: From Highway 52 take Fillmore Street (also known as County Road 12) approximately 1/2 mile to the parking lot.'],
        restrooms: ['At the trailhead in Preston', 'At the Community Center in Harmony'],
        winter: ['Cross-country skiing is popular on this trail in the winter. The trail is partially groomed with 12 miles of set tracks. The tracks begin at the Root River and Harmony-Preston Valley trail junction and follow the trail south just past Co Rd 16.  A Minnesota Ski Pass is required to ski on this trail.'],
        lat: 43.711155,
        long: -92.042778,
        map_latitude: 43.711155,
        map_longitude: -92.042778,
        map_zoom: 11,
        map_zoom_embed: 11,
        created_at: '06/07/2023',
        updated_at: '06/07/2023',
      },
      { 
        _id: new ObjectId('647e11311ba1d11e7e07d243'),
        trail: 'Heartland State Trail',
        trailUses: ['Hiking', 'Biking', 'In-line skating', 'Mountain Biking','Snowmobiling', 'Wheelchair access'],
        naturalSurface: null,
        skiTrail: null,
        atvTrail: null,
        description: `The Heartland State Trail was one of the first rail-to-trail projects in the country. It is a 49 mile multiple-use trail between Park Rapids and Cass Lake. The trail is located entirely on a level abandoned railroad grade, except for a four-mile segment north of Walker that is on sharply rolling terrain for snowmobilers. Bicyclists can follow level road shoulders along Steamboat Loop NW and Cove Lane as marked.
        Both the 27 mile segment connecting Park Rapids and Walker and the 22 mile segment connecting Walker and Cass Lake are paved. The Park Rapids to Walker segment also has a parallel natural surface trail for horseback riding, hiking and mountain biking. The Heartland State Trail also connects with the Paul Bunyan State Trail system and other regional trail systems.`,
        landscape: `Views of lakes, rivers and streams are numerous, and many are accessible from the trail. The trail passes through northern hardwood forests and stands of jack, red, and white pine, as well as the spruce fir forest community. The occasional majestic white pine can be seen towering over the trail.
        Mammals along the trail include whitetail deer, raccoon, red fox, porcupine, beaver and muskrat. The observant visitor may spot coyote, weasel, mink, bobcat or black bear. Many varieties of birds can be seen along the trail including the bald eagle, which has a large population in the Chippewa National Forest and surrounding area.`,
        permits: ['You will need a Horse Pass if you will be horseback riding or carriage driving.', 'You will need a Ski Pass for cross-country skiing on a groomed track. Ungroomed tracks do not require a pass.', 'Snowmobiles must be registered or have a snowmobile state trail sticker.', 'No other fees or passes are required to use the trail.' ],
        parking: ['Park Rapids: Heartland County Park - North 0.25 mile on Mill Street from Highway 34.', 'Dorset: North 1.4 miles on Highway 225 from Highway 34.', 'Nevis: At intersection of County Road 18 and Village Road off Highway 34.', 'Akeley: North from Highway 34 travel 0.1 miles on Hillside Avenue.', 'Walker: South on County Road 12 0.25 miles from Highway 371 to Lake May Drive and Heartland Place south.', 'Erickson\'s Landing: Two miles north of Walker on highway 371.', 'Steamboat Landing: West off Highway 371 travel 0.3 mile on 130st Street northwest.', 'Cass Lake: On the north side of Highway 2 at rest area 2 miles east of Cass Lake and across the highway on south side.'],
        restrooms: ['Most communities provide public restrooms nearby with some in local parks in proximity to the trail. Organizations such as chambers of commerce or tourism agencies provide restroom facilities within some larger communities. Local businesses provide restroom facilities for customers. Portable toilet facilities are often provided in the larger and often used trail rest areas.'],
        winter: ['Studded tracks are allowed on the Heartland State Trail. The trail also provides connections to many miles of groomed snowmobile trails in the Hubbard and Cass counties through the Grant-in-Aid trail system.'],
        lat: 46.956594,
        long:  -95.002508,
        map_latitude: 46.956594,
        map_longitude:  -95.002508,
        map_zoom: 11,
        map_zoom_embed: 11,
        created_at: '06/07/2023',
        updated_at: '06/07/2023',
      },
      { 
        _id: new ObjectId('647e11311ba1d11e7e07d244'),
        trail: 'Luce Line State Trail',
        trailUses: ['Hiking', 'Biking', 'Mountain Biking', 'Horseback','Snowmobiling', 'Wheelchair access'],
        naturalSurface: null,
        skiTrail: null,
        atvTrail: null,
        description: 'The Luce Line State Trail is a 63 mile long former railroad grade that is popular for biking, hiking, horseback riding, mountain biking and snowmobiling. The crushed limestone trail runs from Plymouth 30 miles west to the McLeod/Carver County line, with a parallel trail for horseback riding. From the McLeod/Carver County line to Hutchinson the trail is paved. From Hutchinson to Cedar Mills it is crushed rock, from Cedar Mills to Cosmos it is natural (mowed grass) and from Cosmos to Thompson Lake it is back to crushed rock. Snowmobiles are allowed on the trail west of Stubbs Bay Road.',
        landscape: `Stretching across the varied landscapes of metropolitan and rural Minnesota, the Luce Line is a preserved strip of countryside alive with many varieties of plants and animals. In the east the influence is woodland, a carry-over from the Big Woods that once occupied the area. Rolling stands of sugar maple and basswood, along with many colorful forest floor ground cover plants can be found here. From Hutchinson westward, the Big Woods gives way to remnants of the tall grass prairie, with many prairie plants still visible.
        Wildlife inhabitants range from deer, fox and mink to owls and pheasant. Many adjacent lakes also support ducks and geese. The Luce Line is truly like a jaunt down a quiet country road.`,
        permits: ['You will need a Horse Pass if you will be horseback riding or carriage driving.', 'Snowmobiles must be registered or have a snowmobile state trail sticker.', 'No other fees or passes are required to use the trail. (Skiing on ungroomed trails does not require a Ski Pass.)'],
        parking: ['Carver County Road 127, south of County Road 20.', 'Cedar Mills: Parking lot located on the south side of Hwy 7, east of the grain elevator.', 'Cosmos: Thompson Park offers parking, 252nd Avenue and within Cosmos (on road).', 'Hutchinson: Two options, both located off Highway 7, on each end of the town.', 'Independence: east side of County Road 110, south of County Road 6.', 'Lyndale: off County Road 92.', 'Long Lake: take Old Crystal Bay Road south to Watertown Road, then west to Stubbs Bay Road. Go south 1/4 mile to the parking lot on the west side of the road.', 'Plymouth: off of 10th Avenue N and Vicksburg Lane.', 'Silver Lake: North side of Highway 7 at Park Avenue.', 'Watertown: Just west of the town, off Vega Avenue.', 'Winsted: Babcock Ave/County Road 1 and Kingsley St/County Road 9 (on road).'],
        restrooms: ['Highway 101', 'Willow Drive (Available seasonally on-site from April-November.)', 'County Road 92', 'Old Long Lake Road (Available seasonally on-site from April-November.)', 'Other adjacent city and regional parks along the trail.'],
        winter: ['Skiing is suggested between Vicksburg Lane and Stubbs Bay Road. Ungroomed trails do not require a Ski Pass. Snowmobiles are allowed on the trail west of Stubbs Bay Road, but are prohibited between Vicksburg Lane and Stubbs Bay Road. Be aware of local speed limit restrictions. Snowmobiles must be registered or have a snowmobile state trail sticker.'],
        lat:  44.940501,
        long: -93.741531,
        map_latitude:  44.940501,
        map_longitude: -93.741531,
        map_zoom: 11,
        map_zoom_embed: 11,
        created_at: '06/07/2023',
        updated_at: '06/07/2023',
      },
      { 
        _id: new ObjectId('647e11311ba1d11e7e07d246'),
        trail: 'Matthew Lourey State Trail',
        trailUses: ['Hiking', 'Mountain Biking', 'Horseback','Snowmobiling', 'All-terrain vehicle', 'Off-Highway motorcycle'],
        naturalSurface: null,
        skiTrail: null,
        atvTrail: null,
        description: 'The Matthew Lourey State Trail is a multi-use, natural and gravel surfaced trail that spans approximately 80 miles and passes through forests linking St. Croix State Park with Chengwatana, St. Croix and Nemadji state forests. The entire trail is open to hiking and snowmobiling. Off-highway vehicle riding is allowed on some portions of the trail in the state forests, and horseback riding and mountain biking is allowed in some sections within St. Croix State Park. Some areas may be impassable in summer.',
        landscape: `The trail travels through remote forests and is primarily located on DNR-administered lands, including Nemadji, St. Croix, and Chengwatana state forests, and St. Croix State Park. 
        Common mammals noticed along the trail include whitetail deer, raccoon, red fox, porcupine, beaver, and muskrat. The observant trail user may also spot coyote, timber wolf, weasel, mink, bobcat or black bear.`,
        permits: ['You will need a Horse Pass if you will be horseback riding.', 'You will need a vehicle permit to park in the state park.', 'Snowmobiles must be registered or have a snowmobile state trail sticker.', 'Off-highway vehicles require the proper registration. Non-residents must have the correct non-resident OHV trail pass.', 'No other fees or passes are required to use the trail.'],
        parking: ['Gafvert Campground and Day Use Area', 'Tamarack Forest Road', 'County Road 173', 'Across the MN/WI border in Danbury, WI', 'Township Road 277', 'Township Road 1394', 'Chengwatana Road - Redhorse Lot', 'Chengwatana Spur A - Gravel pit lot', 'County Road 118 (snowmobiles only)'],
        restrooms: [ 'Grace\'s Lake parking lot in St. Croix State Forest', 'Boulder Campground in St. Croix State Forest', 'Tamarack Horse Campground in St. Croix State Forest', 'Mallard Lake lot in St. Croix State Forest ', 'Net Lake Road in Nemadji State Forest', 'Gafvert Campground in Nemadji State Forest', 'Shelter north of the Harlis Road in Nemadji State Forest', 'Shelter at the Yellow Birch and Gandy Dancer Trail junction in Nemadji State Forest', 'Trail junction with the Continental Divide Trail', 'Trail junction with the Kingsdale Trail'],
        winter: ['In the winter, ATV use is permitted from Harliss Road in the Nemadji State Forest to Co. Rd. 173 in the St. Croix State Forest, and in the Chengwatana State Forest as shown on the map. Note that on the Matthew Lourey State Trail and the Nemadji and St. Croix state forest trails, snowmobiles and ATVs are both allowed to ride the trail in winter! ATVs are only allowed to ride when the air temperature is 30°F or below. This helps us keep trails sustainable and increases safety for everyone, including our trail groomers.'],
        lat: 45.07179,
        long: -92.38259,
        map_latitude: 45.07179,
        map_longitude:  -92.38259,
        map_zoom: 11,
        map_zoom_embed: 11,
        created_at: '06/07/2023',
        updated_at: '06/07/2023',
      },
      { 
        _id: new ObjectId('647e11311ba1d11e7e07d247'),
        trail: 'Mill Towns State Trail',
        trailUses: ['Hiking', 'Biking', 'In-line skating', 'Snowmobiling', 'Wheelchair access'],
        naturalSurface: null,
        skiTrail: null,
        atvTrail: null,
        description: 'When complete, the Mill Towns State Trail will connect the cities of Faribault, Dundas, Northfield, Waterford, Randolph, and Cannon Falls, for a distance of approximately 25 miles. The trail will be an important link in the developing southeast Minnesota trail system, connecting the Sakatah Singing Hills State Trail in Faribault with the western end of the Cannon Valley Trail in Cannon Falls.',
        landscape: `Faribault Segment - 1 mile. This trail segment travels from 17th Street NW to Park Avenue, and connects to a network of local trails and city parks. 
        Dundas to Northfield Segment - 3 miles. This trail segment connects with the city of Northfield trails near Babcock and Riverside Park on the north end, and follows the Cannon River to the city of Dundas trailhead and local trails on the south end.        
        Lake Byllesby Regional Park to Cannon Falls Segment - 2 miles. This trail segment runs from 9th Street in Cannon Falls to the Lake Byllesby Dam. To the east, it connects with Hannah’s Bend Park and the city of Cannon Falls trails, which in turn connect to the nearly 20 mile Cannon Valley Trail. To the west, it connects with two county parks, Dakota County’s Lake Byllesby Regional Park and Goodhue County’s Lake Byllesby Park.`,
        permits: ['Snowmobiles must be registered or have a snowmobile state trail sticker.', 'No other fees or passes are required to use the trail. ', 'Parking in some regional parks may incur a fee.'],
        parking: ['Faribault: at the White Sands Park trailhead on the west side of MN Hwy. 21, 1/8 mile north of 7th St. NW.', 'Dundas: at Mill Park and the Mill Towns State Trail trailhead on Railway Street. ', 'Northfield: at Sechler and Riverside Parks.', 'Lake Byllesby: at either of the county parks along the east side of Lake Byllesby.', 'Cannon Falls: at trailhead lot adjacent to the Cannon Valley Fairgrounds, or at Hannah’s Bend Park.'],
        restrooms: ['White Sands Park trailhead in Faribault (seasonally available)', 'Mill Park in Dundas (seasonal portable restroom)', 'Sechler and Riverside Parks in Northfield (seasonally available)', 'Lake Byllesby Park on south side of Lake Byllesby, at Lake Byllesby Regional Park on the north side of Lake Byllesby and at Hannah’s Bend Park in Cannon Falls (seasonally available)'],
        winter: ['The trail is open in the winter but is not groomed for any winter use. Snowshoers and walkers or skiers who don\'t mind not having a groomed trail will enjoy the trail in winter. A separate treadway for snowmobiles is groomed during the winter months between Cannon Falls and Lake Byllesby. There is also a short shared-use segment open for snowmobile use between Dundas and Northfield. Both of these segments connect to many miles of groomed snowmobile trails in the area through the Grant-in-Aid trail system.'],
        lat: 44.389505,
        long: -93.229774,
        map_latitude: 44.389505,
        map_longitude: -93.229774,
        map_zoom: 11,
        map_zoom_embed: 11,
        created_at: '06/07/2023',
        updated_at: '06/07/2023',
      },
      { 
        _id: new ObjectId('647e11311ba1d11e7e07d248'),
        trail: 'Minnesota Valley State Trail',
        trailUses: ['Hiking', 'Biking', 'In-line skating', 'Horseback','Snowmobiling', 'Mountain Biking'],
        naturalSurface: null,
        skiTrail: null,
        atvTrail: null,
        description: 'The multi-use Minnesota Valley State Trail is ideal for hiking, biking, horseback riding, mountain biking and snowmobiling. There are currently two segments of trail, each running through the Minnesota Valley State Recreation Area. The first, longest segment starts in Belle Plaine and ends in Shakopee. This segment is unpaved for 19.5 miles and runs from Belle Paine to the Gifford Lake Unit near Chaska. From Chaska to Fisher Lake in Shakopee, the trail is paved for 9.8 miles. The second, smaller segment begins at Minnesota Bottoms Landing on the Minnesota River, near 35W, and runs for 1.7 miles eastward to Blackdog Lake in Bloomington.',
        landscape: `The Minnesota River Valley is a rich mosaic of plant and animal communities, full of floodplain marshes, wet meadows, fens and lakes. These wetlands are maintained by the river and by the spring-fed streams that drain from the base of the bluffs.
        The hillsides and bluffs support oak forest and oak savanna remnants, as well as outstanding scenic overlooks. As the seasons unfold, you will find spring wildflowers, fall colors, abundant wildlife and the ever-changing river landscape.        
        The Minnesota River may flood when large amounts of rain enter the watershed. The following trail segments are often wet and muddy, so bring proper footwear: West of the Thompson Ferry Unit parking area; west of the Carver Rapids Unit parking area; east of the Chaska parking area; and many sections in the Lawrence Unit.`,
        permits: ['You will need a Horse Pass if you will be horseback riding or carriage driving.', 'Snowmobiles must be registered or have a snowmobile state trail sticker.', 'No other fees or passes are required to use the trail. ', 'You do not need a Ski Pass to ski on ungroomed trails.'],
        parking: ['Gifford Lake: Take U.S. Highway 169 to State Highway 41, turn north toward Chaska and continue 2/3 of a mile past the train tracks. Gifford Lake public water access is on the west side of State Highway 41, before Chaska.', 'Lyndale Avenue Public Water Access: From I-35, take the W 106th Street exit. Head east to Lyndale Avenue and take a right to the south. ', 'Minnesota Valley National Wildlife Refuge, Louisville Swamp Unit: Parking and trail access is available at the Louisville Swamp trailhead. The wildlife refuge is located about 4.5 miles south of Shakopee. Exit Highway 169 onto 145th Street west. Follow the road past the main entrance to the Renaissance Festival and over the next set of railroad tracks. The Louisville Swamp parking lot is located on the left.', 'Minnesota Valley State Recreation Area, Lawrence Unit: Parking is available for the equestrian campground, state trail access, picnic shelter/warming house, Strait House historic site, hiking and cross-country ski trails. Take U.S. Highway 169 to Jordan. At the traffic light turn north onto County Road 9, and then left onto Township Road 57.', 'Shakopee/Huber Park: The city park is located at First Avenue and Fillmore Street.', 'Shakopee/Memorial Park: The city park is located at 1801 East County Road 101.', 'Thompson Ferry Access: Take U.S. Highway 169 to Jordan, turn north onto County Road 9. Thompson Ferry Access and parking area is on the east side of the road just before the bridge. Parking for horse trailers and other vehicles is on the west side of the road just before the bridge.', 'Trail Site 2: Take U.S. Highway 169 to State Highway 41, turn north toward Chaska. The parking lot is on the east side of State Highway 41'],
        restrooms: ['Day-use area. Lawrence Unit of the Minnesota Valley State Recreation Area.', 'Other adjacent city and regional parks along the Minnesota River.'],
        winter: ['Cross-country skiing is available along the trail and in the Minnesota Valley State Recreation Area, but there are no groomed trails. Snowmobiles are allowed on the Minnesota Valley State Trail, which connects to local snowmobile trail systems. Note: Snowmobiles are not allowed on the Minnesota Valley State Trail in Bloomington.'],
        lat: 44.777932,
        long: -93.594149,
        map_latitude: 44.777932,
        map_longitude: -93.594149,
        map_zoom: 11,
        map_zoom_embed: 11,
        created_at: '06/07/2023',
        updated_at: '06/07/2023',
      },
      { 
        _id: new ObjectId('647e11311ba1d11e7e07d249'),
        trail: 'Paul Bunyan State Trail',
        trailUses: ['Hiking', 'Biking', 'In-line skating', 'Mountain Biking','Snowmobiling', 'Wheelchair access'],
        naturalSurface: null,
        skiTrail: null,
        atvTrail: null,
        description: 'The Paul Bunyan State Trail is 115 miles long, not including a couple of short on-road connections through the cities of Baxter and Bemidji. Extending all the the way from Crow Wing State Park to Lake Bemidji State Park, it is the longest of Minnesota\'s state trails and the longest continuously paved rail-trail in the country. It connects with the 8 mile Heartland State Trail, and at Lake Bemidji State Park it connects to the Blue Ox Trail, an unpaved motorized trail for snowmobiling and off-highway vehicle riding that extends northeast to International Falls.',
        landscape: `Primarily located on a former Burlington Northern Railroad grade, the trail is generally level and wheelchair accessible with the exception of the nine mile segment that passes through the Chippewa National Forest. This segment has many rolling hills and curves with grades reaching 8%, and may be challenging to some users. The Shingobee Connection paved trail is an easier route to Walker, although there are a couple of short, very steep hills and some paved road shoulder sections of trail.`,
        permits: ['Snowmobiles must be registered or have a snowmobile state trail sticker.', 'You will need a vehicle permit to park in a state park.', 'No other fees or passes are required to use the trail.'],
        parking: ['La Porte: Parking is available in La Porte.', 'Jenkins: Parking is available in Jenkins.', 'Guthrie: Parking is available in Guthrie.', 'Crow Wing State Park:  Parking available within the park.', 'Backus: Parking is available in Backus.', 'North Country Trail: Parking is located 5 miles west of Highway 371 on Cass County Road 50.', 'Pequot Lakes: From Highway 371, exit onto County Road 11, and go west into Pequot Lakes to the stoplight at the intersection with Patriot Avenue. Turn left (south) onto Patriot Avenue, then take the next left (east) onto Woodman Street for 1/2 block. The parking lot is on the left', 'Walker: A parking area is located southwest of Walker on State Highway 34 just south of the intersection of the Paul Bunyan and Heartland Trails, approximately 4 miles east of Akeley.'],
        restrooms: ['Most communities provide public restrooms nearby with some in local parks in proximity to the trail.  Organizations such as chambers of commerce or tourism agencies provide restroom facilities within some larger communities. Local businesses provide restroom facilities for customers. Portable toilet facilities are often provided in the larger and often used trail rest areas.'],
        winter: ['Studded tracks are allowed on the Paul Bunyan State Trail. The trail provides connections to many miles of groomed snowmobile trails in the Hubbard County Grant-in-Aid trail system.'],
        lat: 47.2213452,
        long:  -95.043904,
        map_latitude: 47.2213452,
        map_longitude:  -95.043904,
        map_zoom: 11,
        map_zoom_embed: 11,
        created_at: '06/07/2023',
        updated_at: '06/07/2023',
      },
      { 
        _id: new ObjectId('647e11311ba1d11e7e07d250'),
        trail: 'Root River State Trail',
        trailUses: ['Hiking', 'Biking', 'In-line skating', 'Skiing', 'Wheelchair access'],
        naturalSurface: null,
        skiTrail: null,
        atvTrail: null,
        description: 'The paved Root River State Trail meanders 42 miles alongside the Root River from Fountain to Houston. Constructed on an abandoned railroad, the trail is generally level and wheelchair accessible except for a steep half-mile segment between Vinegar Ridge and Houston that may be challenging for some visitors.',
        landscape: `Part of the Blufflands Trail System, the trail provides outstanding views of the soaring limestone bluffs of the Root River Valley. The trail rises and falls with the bluffs, winding through historic towns tucked into hillsides, past rolling farm fields, milling districts, and relics of the railroad's heyday. Lush and verdant stretches offer views of the area's natural beauty.
        Wildlife is abundant, and sightings of wild turkey, deer, hawks and turkey vultures are common. Rattlesnakes can occasionally be found on rock outcrops, along the river bottoms, or sunning themselves on the trail. They are a state threatened and protected species, and should be left alone.        
        Historical buildings and rural communities along the trail provide sites of interest as well as many services. Campgrounds, bed-and-breakfasts, restaurants, museums, outfitters and unique stores can be found in many of the trail towns.`,
        permits: ['You will need a Ski Pass for cross-country skiing. No other fees or passes are required to use the trail'],
        parking: ['Fountain: From Highway 52 take County Road 8 about one mile to the parking lot near the city park/softball field.', 'Lanesboro: Parking is available in the lot next to the Bass Pond off of County Road 8. Additional parking is available along the streets and at the parking lot by the Community Center/Sylvan Park.', 'Whalan: Street parking.', 'Peterson: From Highway 16, turn into Peterson on Mill Street, go 1/2 mile to Fillmore Street, and turn left to the city campground/softball field. Parking is also available along the streets.', 'Rushford: From Highway 16, turn north on Elm Street and go one block. The parking lot is at the restored railroad depot.', 'Houston: Turn west on Plum street of of Highway 76 and go one block to the Nature Center.'],
        restrooms: ['at the parking lots in Fountain and Peterson', 'at the trail centers in Lanesboro, Rushford and Houston'],
        winter: ['at the parking lots in Fountain and Peterson'],
        lat: 43.76857719,
        long: -91.5698654,
        map_latitude: 43.76857719,
        map_longitude: -91.5698654,
        map_zoom: 11,
        map_zoom_embed: 11,
        created_at: '06/07/2023',
        updated_at: '06/07/2023',
      },
      { 
        _id: new ObjectId('647e11311ba1d11e7e07d251'),
        trail: 'Sakatah Singing Hills State Trail',
        trailUses: ['Hiking', 'Biking', 'In-line skating', 'Horseback','Snowmobiling', 'Wheelchair access'],
        naturalSurface: null,
        skiTrail: null,
        atvTrail: null,
        description: 'The Sakatah Singing Hills State Trail is a paved, 39 mile multiple-use trail which has been developed on an abandoned railroad grade. The trail begins at Lime Valley Road near State Highway 14, joins the Minnesota River Trail in Mankato, follows a signed route on city streets through Waterville, passes through three miles of Sakatah Lake State Park, and ends east of Interstate 35 in Faribault. It is generally level and wheelchair accessible. Horses can use a parallel treadway from Lime Valley Road to the County Road 12 bridge.',
        landscape: `The trail lies in the transition zone between what was once the "Big Woods" and the vast prairies. Remnants of these plant communities can still be found scattered throughout what is now cultivated land.
        Sakatah Lake State Park is along the trail, and provides a separate bicycling campground, picnic grounds, boat access, and additional hiking trails. There are several other lakes and public parks within an easy ride of the trail.`,
        permits: ['You will need a Horse Pass if you will be horseback riding or carriage driving.', 'Snowmobiles must be registered or have a snowmobile state trail sticker.', 'You will need a vehicle permit to park in a state park.', 'No other fees or passes are required to use the trail.'],
        parking: ['Mankato: North on County Road 57 (Riverfront Drive) to Lime Valley Road; 1/4 mile north.', 'Mankato: North on State Highway 22.', 'Eagle Lake: West on State Highway 14 to County Road 86; one mile north.', 'Madison Lake: State Highway 60 to Main Street, three blocks north on Main Street.', 'Elysian: Sakatah Singing Hills State Trail Wayside Rest Area.', 'Waterville: State Highway 60 to State Highway 13; 1/4 mile north on 13.', 'Morristown: State Highway 60 to County Road 16; west on State Highway 60 1/4 mile.', 'Shager County Park: On State Highway 60.', 'Faribault: State Highway 60 and County Road 21; north on County Road 21 1/2 mile.'],
        restrooms: ['Elysian: Year-round wheelchair accessible wayside rest building with running water.', 'Faribault: Year-round wheelchair accessible wayside rest building with running water.', 'Sakatah Lake State Park: Seasonal bathrooms with running water. (Not available in winter.)', 'Wheelchair accessible portable toilets are available Mid-May to Labor Day at the Highway 22, Madison Lake, Morristown, and Shager Park parking Lots. (Not available in winter.)'],
        winter: ['The entire 39 mile trail is open to hiking, cross-country skiing, and snowmobiling in the winter.'],
        lat: 44.259954,
        long: -93.791656,
        map_latitude: 44.259954,
        map_longitude: -93.791656,
        map_zoom: 11,
        map_zoom_embed: 11,
        created_at: '06/07/2023',
        updated_at: '06/07/2023',
      },
      { 
        _id: new ObjectId('647e11311ba1d11e7e07d252'),
        trail: 'Shooting Star State Trail',
        trailUses: ['Hiking', 'Biking', 'In-line skating', 'Wheelchair access'],
        naturalSurface: null,
        skiTrail: null,
        atvTrail: null,
        description: 'The Shooting Star State Trail is currently paved for about 29 miles, between LeRoy and Austin. It begins in the city of LeRoy, travels north through Lake Louise State Park, then west toward the communities of Taopi, Adams, and Rose Creek. There is a short break in the trail in Rose Creek between City Hall and Rose Creek Wayside Park. It picks up again in Rose Creek Wayside Park and travels west and north, primarily in state and county highway right-of-way, until it reaches the intersection of 28th Street NE and I-90. Just across the 28th Street bridge over I-90 is a paved path connecting to the Jay C. Hormel Nature Center in Austin. When complete, the trail will also connect with the community of Lyle (south of Austin) and the Wapsi-Great Western Trail in Iowa (south of Taopi)',
        landscape: `Current and future portions of the trail will parallel Highway 56, also known as the Shooting Star Wildflower and Historic Route Scenic Byway. The native wildflowers and grasses are a highlight of this byway and trail. Most tallgrass prairie has been taken for agricultural use, but prairie remnants are places where you can find prairie smoke, rattlesnake master and wild indigo, sunflowers, asters, goldenrods, and blazing stars.
        The trail connects to Lake Louise State Park.  When the Upper Iowa River was dammed to provide power for a grist mill, a lake was formed. The mill was eventually abandoned, and the site first became Wildwood Park, and then became the state park.`,
        permits: ['You will need a vehicle permit to park in a state park.', 'No other fees or passes are required to use the trail.'],
        parking: ['In LeRoy: east of County Road 14 on Lowell Street', 'At Rowe Pit: north of LeRoy off County Road 14', 'In Lake Louise State Park: (vehicle permit required)', 'In Taopi: south side of Highway 56, between Maple and Main Streets', 'In Adams: south side of Highway 56 (West Main Street) just west of 5th Street', 'At Rose Creek in Wayside Park: from 4th Street or from Highway 56', 'At J.C. Hormel Nature Center: off 21st Street'],
        restrooms: ['Adams City Park: Located on the south side of Highway 56 (West Main Street) just west of 5th Street', 'Jay C. Hormel Nature Center: off 21st Street', 'Lake Louise State Park: Lake Louise picnic area and swimming beach (vehicle permit required)', 'Rose Creek Wayside Park: from 4th Street or from Highway 56', 'City of Taopi'],
        winter: ['Cross-country skiing, snowshoeing and hiking are permitted winter uses. Trails are not groomed or packed. There is no snowmobiling on the trail.'],
        lat: 43.420961,
        long: -92.853112,
        map_latitude: 43.420961,
        map_longitude: -92.853112,
        map_zoom: 11,
        map_zoom_embed: 11,
        created_at: '06/07/2023',
        updated_at: '06/07/2023',
      },
      { 
        _id: new ObjectId('647e11311ba1d11e7e07d253'),
        trail: 'David Dill/Taconite & Taconite State Trails',
        trailUses: ['Hiking', 'Biking', 'Mountain Biking', 'Horseback','Snowmobiling', 'All-terrain Vehicle', 'Off-Highway motorcycle'],
        naturalSurface: null,
        skiTrail: null,
        atvTrail: null,
        description: 'The Taconite State Trail stretches 165 miles from Grand Rapids to Ely and intersects with the David Dill/Arrowhead State Trail just west of Lake Vermillion. The David Dill/Taconite State Trail extends from the David Dill/Arrowhead State Trail to Ely. The first six miles from Grand Rapids are paved for biking and in-line skating. The remainder of the natural surface trail is used primarily for snowmobiling in the winter. The trail goes through a few areas that have standing water in the summer, however portions of the trail are suitable for horseback riding, hiking, and mountain biking. Off-highway vehicle riding is allowed on some trail portions.',
        landscape: `The Taconite Trail winds through forests of birch and aspen intertwined with pine, leading the visitor by many isolated lakes and streams. From Grand Rapids heading north, you see the impact of the taconite and iron mining industry. In the northern portion of the trail the terrain is rolling and tree covered as it winds through state and national forest land. Trail users may see a ridge of solid white pine changing to a ravine of mixed hardwoods, then a ridge of aspen, birch and basswood blended with maples.
        At the trail intersection east of the David Dill/Arrowhead State Trail, this segment is called the David Dill/Taconite State Trail.        
        Eight trail waysides and picnic facilities offer scenic vistas of the hills, lakes and rivers of this area. The trail links to Bear Head Lake, Lake Vermilion-Soudan Underground Mine, and McCarthy Beach state parks. The landscape in and around Bear Head Lake State Park is very rolling and rocky, with elevations ranging from 1,450 - 1,590 feet.        
        The landscape of the area is a result of the underlying geology. The area's bedrock formation is known as the Canadian Shield. It was formed by volcanic action approximately 2.7 billion years ago, and is some of the oldest rock on Earth. Later, ancient seas laid down the valuable iron ore that is still mined in the area today. Further volcanic activity swept away the sea and formed two mountain ranges. The advancing and receding of glaciers and millions of years of erosion have worn the mountains down, leaving behind the rugged landscape now found along much of the trail.`,
        permits: ['You will need a Horse Pass if you will be horseback riding or carriage driving.', 'Snowmobiles must be registered or have a snowmobile state trail sticker.', 'No other fees or passes are required to use the trail.'],
        parking: ['McCarthy Beach State Park', 'Minnesota Highway 73', 'U.S. Highway 53', 'Minnesota Highway 1','Minnesota Highway 169, Peyla', 'Minnesota Highway 135, Tower'],
        restrooms: ['Bear Head Lake State Park: Parking and interpretive center located within the state park.', 'George Washington State Forest: Campgrounds offer seasonal facilities, check ahead.', 'McCarthy Beach State Park: Parking and campgrounds located within the state park.', 'Soudan Underground Mine State Park: Parking and interpretive center located within the state park.', 'Restrooms and amenities are also available in the towns along the trail.'],
        winter: null,
        lat: 47.5157702,
        long: -93.364084,
        map_latitude: 47.5157702,
        map_longitude: -93.364084,
        map_zoom: 11,
        map_zoom_embed: 11,
        created_at: '06/07/2023',
        updated_at: '06/07/2023',
      },
      { 
        _id: new ObjectId('647e11311ba1d11e7e07d254'),
        trail: 'Willard Munger State Trail',
        trailUses: ['Hiking', 'Biking', 'In-line skating', 'Mountain Biking', 'Horseback','Snowmobiling', 'Wheelchair access'],
        naturalSurface: null,
        skiTrail: null,
        atvTrail: null,
        description: 'The Willard Munger State Trail is a collection of multiple use trails between Hinckley and Duluth. It consists of interconnecting trails offering hiking, bicycling, in-line skating, snowmobiling and horseback riding. It highlights the picturesque scenery and rich history of East Central Minnesota. Some of the trail follows the route of the railroad that saved many lives in the historic Hinckley and Cloquet fires in the nineteenth century.',
        landscape: `This trail passes through northern hardwood forests and stands of jack, red, and white pine, as well as the spruce fir community. Ranges of hills pocked with countless lakes and bogs cover the region.
        Common mammals noticed along the trail include whitetail deer, raccoon, red fox, porcupine, beaver and muskrat. The observant trail user may also spot coyote, timber wolf, weasel, mink, bobcat or black bear.        
        The 70 mile Hinckley - Duluth segment of the trail is completely paved, and passes near Banning State Park and Moose Lake State Park, through the towns of Finlayson, Willow River and Moose Lake, General C.C. Andrews State Forest, and through the spectacular scenery of Jay Cooke State Park. The northeast portion of the trail provides scenic views of the St. Louis River and the twin ports of Duluth and Superior.`,
        permits: ['You will need a Horse Pass if you will be horseback riding or carriage driving.', 'Snowmobiles must be registered or have a snowmobile state trail sticker.', 'You will need a require a vehicle permit to park in a state park.', 'No other fees or passes are required to use the trail.'],
        parking: ['Carlton: one block south of Highway 210 on County Road 1, or at Hemlock Ravine SNA, four miles east of Carlton on Highway 210.', 'Duluth: at the northern trailhead on Grand Ave. (Hwy 23) and 75th Avenue West, behind the Munger Hotel', 'General C.C. Andrews State Forest: Dago Lake Day Use Area, McCormick Lake Day Use Area, Willow River Campground', 'Hinckley: at the southern trailhead, one block north of the Hinckley Fire Museum at the intersection of Highway 61 and County Road 18', 'Jay Cooke State Park (vehicle permit required)', 'Moose Lake State Park (vehicle permit required)'],
        restrooms: ['General C.C. Andrews State Forest: Dago Lake Day-Use Area, Willow River Campground', 'Jay Cooke State Park (vehicle permit required)', 'Moose Horn River Water Access Site: located in Barnum, on County Highway 6', 'Moose Lake State Park (vehicle permit required)', 'Sand Lake Water Access Site: located in Sturgeon Lake, two miles north of the city', 'Public water access locations often have seasonal toilets available.', 'Facilities may also be available in city and regional parks along the state trail. (May require additional fee.)'],
        winter: null,
        lat: 46.449989,
        long: -92.768661,
        map_latitude: 46.449989,
        map_longitude: -92.768661,
        map_zoom: 11,
        map_zoom_embed: 11,
        created_at: '06/07/2023',
        updated_at: '06/07/2023',
      }
    ];

    await Trail.deleteMany({}); // Clear existing trails
    await Trail.insertMany(trailData); // Create new trails
    console.log('Trails seeded successfully!');
  } catch (error) {
    console.error('Error seeding trails:', error);
  } 
}


module.exports = seedTrails;